version: 2.1 # use CircleCI 2.0
jobs: # a collection of steps
  build_and_test: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/workspace # directory where steps will run
    docker: # run the steps with Docker
      - image: node:latest # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest

workflows:
  main:
    jobs:
      - build_and_test
